=== Limpan0/1ME323lab/L1/music_genres.dtd
<!-- 
music_genres
    song+
        title
        artist*
            name
            birth
            gender *
                attr: (male | female)
            link
                attr: url
        group*
            formed
            link attr: url
        album?
            attr: img
            attr: caption?
        release_date
        duration
-->

<!ELEMENT music_genres (song+)>
    <!ELEMENT song (title, artist*, group*, link, album?, release_date, duration)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT artist (name, birth, gender*)>
            <!ELEMENT name (#PCDATA)>
            <!ELEMENT birth (#PCDATA)>
            <!ELEMENT gender (#PCDATA)>
                <!ATTLIST gender type (male|female) #IMPLIED>
        <!ELEMENT group (group_name, formed)>
            <!ELEMENT group_name (#PCDATA)>
            <!ELEMENT formed (#PCDATA)>
        <!ELEMENT link EMPTY>
                <!ATTLIST link url CDATA #REQUIRED>
        <!ELEMENT album EMPTY>
            <!ATTLIST album img CDATA #REQUIRED caption CDATA #IMPLIED>
        <!ELEMENT release_date (#PCDATA)>
        <!ELEMENT duration (#PCDATA)>

=== Limpan0/1ME323lab/L1/classical.XML
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE music_genres SYSTEM "music_genres.dtd">

<music_genres>
    
    <song>
        <title>Symphony No. 5</title>
        <artist>
            <name>Ludwig van Beethoven</name>
            <birth>16-12-1770</birth>
            <gender type="male"/>
        </artist>
        <link url="https://www.allmusic.com/artist/ludwig-van-beethoven-mn0000536126" />
        <release_date>1809</release_date>
        <duration>38:10</duration>
    </song>

    <song>
        <title>Symphony No. 40</title>
        <artist>
            <name>Wolfgang Amadeus Mozart</name>
            <birth>27-01-1756</birth>
            <gender type="male"/>
        </artist>
        <link url="https://www.allmusic.com/artist/wolfgang-amadeus-mozart-mn0000026350"/>
        <release_date>1788</release_date>
        <duration>26:36</duration>
    </song>

    <song>
        <title>Four Seasons</title>
        <artist>
            <name>Antonio Vivaldi</name>
            <birth>04-03-1678</birth>
            <gender type="male"/>
        </artist>
        <link url="https://www.allmusic.com/artist/antonio-vivaldi-mn0000685058/biography" />
        <release_date>1725</release_date>
        <duration>~41:00</duration>
    </song>
    
    <song>
        <title>Sonata</title>
        <artist>
            <name>Johann Sebastian Bach</name>
            <birth>21-03-1685</birth>
            <gender type="male"/>
        </artist>
        <link url="https://www.allmusic.com/artist/johann-sebastian-bach-mn0000075140" />
        <release_date>1720</release_date>
        <duration>16:36</duration>
    </song>

</music_genres>

=== Limpan0/1ME323lab/L1/rock.XML
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE music_genres SYSTEM "music_genres.dtd">

<music_genres>
    
    <song>
        <title>Eye of the Tiger</title>
        <group>
            <group_name>Survivor</group_name>
            <formed>1978</formed>
        </group>
        <link url="https://www.allmusic.com/artist/survivor-mn0000039637"/>
        <album img="bilder/eyeofthetiger.jpg" caption="Eye of the Tiger cover"></album>
        <release_date>1982</release_date>
        <duration>04:06</duration>
    </song>

    <song>
        <title>Paint It Black</title>
        <group>
            <group_name>The Rolling Stones</group_name>
            <formed>1962</formed>
        </group>
        <link url="https://www.allmusic.com/artist/the-rolling-stones-mn0000894465"/>
        <album img="bilder/paintitblack.jpg" caption="Paint It Black cover"></album>
        <release_date>1964</release_date>
        <duration>03:20</duration>
    </song>

    <song>
        <title>Good Rockin' Tonight</title>
        <artist>
            <name>Elvis Presley</name>
            <birth>08-01-1935</birth>
            <gender type="male"/>
        </artist>
        <link url="https://www.allmusic.com/artist/elvis-presley-mn0000180228"/>
        <album img="bilder/goodrockintonight.jpg" caption="Good Rockin' Tonight Cover"></album>
        <release_date>1954</release_date>
        <duration>02:12</duration>
    </song>

    <song>
        <title>Dancing in the Dark</title>
        <artist>
            <name>Bruce Springsteen</name>
            <birth>23-09-1949</birth>
            <gender type="male"></gender>
        </artist>
        <link url="https://www.allmusic.com/artist/bruce-springsteen-mn0000530745"/>
        <album img="bilder/dancinginthedark.jpg" caption="Dancing in the Dark cover"></album>
        <release_date>1984</release_date>
        <duration>04:01</duration>
    </song>
    
</music_genres>

=== Limpan0/1ME323lab/L1/electric.XML
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE music_genres SYSTEM "music_genres.dtd">

<music_genres>
    
    <song>
        <title></title>
        <artist>
            <name></name>
            <age></age>
            <gender type="male"></gender>
        </artist>
        <group>
            <formed></formed>
        </group>
        <album img="" caption=""></album>
        <release_date></release_date>
        <duration></duration>
    </song>

    <song>
        <title></title>
        <artist>
            <name></name>
            <age></age>
            <gender type="male"></gender>
        </artist>
        <group>
            <formed></formed>
        </group>
        <album img="" caption=""></album>
        <release_date></release_date>
        <duration></duration>
    </song>

    <song>
        <title></title>
        <artist>
            <name></name>
            <age></age>
            <gender type="male"></gender>
        </artist>
        <group>
            <formed></formed>
        </group>
        <album img="" caption=""></album>
        <release_date></release_date>
        <duration></duration>
    </song>

    <song>
        <title></title>
        <artist>
            <name></name>
            <age></age>
            <gender type="male"></gender>
        </artist>
        <group>
            <formed></formed>
        </group>
        <album img="" caption=""></album>
        <release_date></release_date>
        <duration></duration>
    </song>

</music_genres>
